name: tahap1
description: "tahap 1 bimbingan karir."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.23
  image_picker: ^1.1.2
  intl: ^0.20.1
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
